#!/bin/zsh
rm ../IntegralRN_ios_bundle/index.ios.js ../IntegralRN_a_bundle/index.android.js ../IntegralRN_ios_bundle/index.ios.zip

mv ../IntegralRN_ios_bundle/ios.bundle ../IntegralRN_ios_bundle/index.ios.js
mv ../IntegralRN_a_bundle/android.bundle ../IntegralRN_a_bundle/index.android.js

cd ../IntegralRN_ios_bundle
zip -r -X index.ios.zip index.ios.js

cd ../Integral
