export default {
  THEME_CHANGE: "THEME_CHANGE",
  THEME_INIT: "THEME_INIT",
  POPULAR_REFRESH: "POPULAR_REFRESH",//刷新成功
  POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
  POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
  POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",//上拉加载成功
  POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",//上拉加载失败
  TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",
  TRENDING_REFRESH: "TRENDING_REFRESH",
  TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
  TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
  TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
  TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
}